### ISSUE TITLE
Correct Codacy Issues

### ISSUE THREAD

**Issue by martinhuszti** [BME-MIT-IET/BudgetAnomalia-iet-2019#7]

**Comment by martinhuszti** [comment]
I'm fixing read.me now!

**Comment by martinhuszti** [comment]
Commit : cd93c08026a1200b9d2a754bb370477cf4dcea8e
Its Fixed.

**Comment by futobarna** [comment]
Commit: 3479182c78415eb484a61d138c9a2611331b45d1
Fixed the last detected problems in the test file.

**Comment by suledani97** [comment]
Fixed the last detected problem in the main file.
